@json_type = application/json

### get token
# @name  get_token
POST http://localhost:8000/auth-token/ HTTP/1.1
Content-Type: application/json

{
    "username":"test_user",
    "password":"test123"
}
### details about user
@auth_token = {{get_token.response.body.token}}
###
GET http://localhost:8000/api/users/me/ HTTP/1.1
Authorization: Token {{auth_token}}

###
GET http://localhost:8000/api/users/admin/ HTTP/1.1
Authorization: Token {{auth_token}}

### create file
POST http://localhost:8000/api/files/
Authorization: Token {{auth_token}}
{
    "name" : "test file",
    ""
}

### get file details
GET http://localhost:8000/api/files/1
Authorization: Token {{auth_token}}

### get entities inside folder by ID (user should have access of the folder)
GET http://localhost:8000/api/utility/get_entities?folder=3
Authorization: Token {{auth_token}}
