@json_type = application/json

### get token
# @name  get_token
POST http://localhost:8000/auth-token/ HTTP/1.1
Content-Type: application/json

{
    "username":"test_user",
    "password":"test123"
}
### details about user
@auth_token = {{get_token.response.body.token}}
###
GET http://localhost:8000/api/users/me/ HTTP/1.1
Authorization: Token {{auth_token}}

###
GET http://localhost:8000/api/users/admin/ HTTP/1.1
Authorization: Token {{auth_token}}

### create file
POST http://localhost:8000/api/files/
Authorization: Token {{auth_token}}
{
    "name" : "test file",
    ""
}

### get file details
GET http://localhost:8000/api/files/7/
Authorization: Token {{auth_token}}

### get entities inside folder by ID (user should have access of the folder)
GET http://localhost:8000/api/utility/get_entities?folder=5
Authorization: Token {{auth_token}}

### shared with me
GET http://localhost:8000/api/utility/shared_with_me/
Authorization: Token {{auth_token}}

### view access
GET http://localhost:8000/api/utility/share/file/1-7/ HTTP/1.1
Content-Type: application/json
Authorization: Token {{auth_token}}

### share access
POST http://localhost:8000/api/utility/share/file/ HTTP/1.1
Content-Type: application/json
Authorization: Token {{auth_token}}

{
    "file": 7,
    "user": 1,
    "type": "viewer"
}

### update access
PATCH http://localhost:8000/api/utility/share/file/1-7/
Content-Type: application/json
Authorization: Token {{auth_token}}

{
    "type": "editor"
}

### delete access
DELETE http://localhost:8000/api/utility/share/file/1-7/
Content-Type: application/json
Authorization: Token {{auth_token}}

### view folder access
POST http://localhost:8000/api/utility/share/folder/ HTTP/1.1
Content-Type: application/json
Authorization: Token {{auth_token}}

{
    "folder": 9,
    "user": 1,
    "type": "viewer"
}

###
DELETE http://localhost:8000/api/utility/share/folder/1-9/
Content-Type: application/json
Authorization: Token {{auth_token}}
###
GET http://13.233.133.41:8000/admin/