# Generated by Django 4.0.8 on 2022-12-13 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('file_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ManyToManyField(related_name='files', related_query_name='file', through='file_system.FileAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.ManyToManyField(related_name='folders', related_query_name='folder', through='file_system.FolderAccess', to=settings.AUTH_USER_MODEL),
        ),
    ]
