# Generated by Django 4.0.8 on 2022-12-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0002_remove_file_ext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='size',
        ),
    ]
