# Generated by Django 4.0.8 on 2022-12-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0002_file_user_folder_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='user',
            new_name='users',
        ),
    ]
