# Generated by Django 4.0.8 on 2022-12-14 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0003_rename_user_file_users_rename_user_folder_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaccess',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access', to='file_system.file'),
        ),
        migrations.AlterField(
            model_name='folderaccess',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access', to='file_system.folder'),
        ),
    ]
