# Generated by Django 4.0.8 on 2022-12-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0004_alter_fileaccess_file_alter_folderaccess_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ext',
            field=models.CharField(default='nan', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
