# Generated by Django 4.0.8 on 2022-12-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0005_file_ext_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='ext',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
    ]
