# Generated by Django 4.0.8 on 2022-12-15 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_system', '0006_alter_file_ext_alter_file_size'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='file',
            name='name_folder_unique_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='fileaccess',
            name='file_user_unique_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='folder',
            name='folder_parent_unique_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='folderaccess',
            name='folder_user_unique_constraint',
        ),
        migrations.AlterField(
            model_name='fileaccess',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='file_system.file'),
        ),
        migrations.AlterField(
            model_name='fileaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folderaccess',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='file_system.folder'),
        ),
        migrations.AlterField(
            model_name='folderaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'folder', 'ext')},
        ),
        migrations.AlterUniqueTogether(
            name='fileaccess',
            unique_together={('user', 'file')},
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='folderaccess',
            unique_together={('user', 'folder')},
        ),
    ]
