# Generated by Django 4.0.8 on 2022-12-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0007_remove_file_name_folder_unique_constraint_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'folder')},
        ),
    ]
