# Generated by Django 4.0.8 on 2022-12-15 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0008_alter_file_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaccess',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_system.file'),
        ),
        migrations.AlterField(
            model_name='folderaccess',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_system.folder'),
        ),
    ]
