# Generated by Django 4.0.8 on 2022-12-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0009_alter_fileaccess_file_alter_folderaccess_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaccess',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folderaccess',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
