# Generated by Django 4.0.8 on 2022-12-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0010_fileaccess_slug_folderaccess_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderaccess',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
