# Generated by Django 4.0.8 on 2022-12-15 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('file_system', '0011_alter_folderaccess_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='users',
            field=models.ManyToManyField(related_name='files', through='file_system.FileAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileaccess',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='file_system.file'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='users',
            field=models.ManyToManyField(related_name='folders', through='file_system.FolderAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folderaccess',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='file_system.folder'),
        ),
    ]
