# Generated by Django 4.0.8 on 2022-12-15 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0012_alter_file_users_alter_fileaccess_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='folder',
            new_name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'parent')},
        ),
    ]
