# Generated by Django 4.0.8 on 2022-12-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0013_rename_folder_file_parent_alter_file_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaccess',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
